# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7664122110aaf29c93f273425ce406920a0845e36aedee6b11d5a415b29a1b6a192484ca61974310d5d117e7e863b4ef4eead0d3b8a8808a7b138b348b5ae61

test:
  secret_key_base: b5f547e12c42582c4380cf6ff136bfebf0e016aec904402f5c59ee3d8deb02955bd7281b3eee309b3d41b4e2fe2286265820716f319e017be599f676b30e1fcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
